// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqzT1FrSoTJsStKW3CsgqEaewr0QfeqaI',
    appId: '1:299611344278:web:00fc400e29a0de584e61b7',
    messagingSenderId: '299611344278',
    projectId: 'airport-travel-app',
    authDomain: 'airport-travel-app.firebaseapp.com',
    storageBucket: 'airport-travel-app.firebasestorage.app',
    measurementId: 'G-BGMMJZWKMV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxoFPBGfaDjiVOD3OUbl453N941-2pVmI',
    appId: '1:299611344278:android:e28d33f75ba33d6b4e61b7',
    messagingSenderId: '299611344278',
    projectId: 'airport-travel-app',
    storageBucket: 'airport-travel-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAByZH_hBVyktyU9-HS2OcJYN652yLisYg',
    appId: '1:299611344278:ios:2ade603ce81f640f4e61b7',
    messagingSenderId: '299611344278',
    projectId: 'airport-travel-app',
    storageBucket: 'airport-travel-app.firebasestorage.app',
    iosBundleId: 'com.example.airportTravelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAByZH_hBVyktyU9-HS2OcJYN652yLisYg',
    appId: '1:299611344278:ios:2ade603ce81f640f4e61b7',
    messagingSenderId: '299611344278',
    projectId: 'airport-travel-app',
    storageBucket: 'airport-travel-app.firebasestorage.app',
    iosBundleId: 'com.example.airportTravelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqzT1FrSoTJsStKW3CsgqEaewr0QfeqaI',
    appId: '1:299611344278:web:4c46043280b763334e61b7',
    messagingSenderId: '299611344278',
    projectId: 'airport-travel-app',
    authDomain: 'airport-travel-app.firebaseapp.com',
    storageBucket: 'airport-travel-app.firebasestorage.app',
    measurementId: 'G-43MWP6TQTN',
  );
}
